server:
  port: 8097
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: servicio-customer
          uri: http://localhost:8090
          predicates:
            - Path=/api/customer/**
        - id: servicio-customer
          uri: http://localhost:8090
          predicates:
            - Path=/api/customerbusiness/**
        - id: servicio-Account
          uri: lb://servicio-Account
          predicates:
            - Path=/api/savings/**
