server:
  port: 8097
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: servicio-customer
          uri: http://localhost:8790
          predicates:
            - Path=/api/customer/** , Path=/api/customerbusiness/**
        - id: servicio-account
          uri: http://localhost:8791
          predicates:
            - Path=/api/savings/**