server:
  port: 8097
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: SERVICIO-CUSTOMER
          uri: lb://servicio-customer
          predicates:
            - Path=/api/customer/**
        - id: SERVICIO-ACCOUNT
          uri: lb://servicio-account
          predicates:
            - Path=/api/savings/**