spring:
  cloud:
    gateway:
      routes:
      
        - id: servicio-customer
          uri: http://localhost:8090/api/customer
          predicates:
          - Path=/api/customer/**
          filters: StripPrefix=2


        - id: servicio-customer
          uri: http://localhost:8090/api/customerbusiness
          predicates:
          - Path=/api/customerbusiness/**
          filters: StripPrefix=2


        - id: servicio-Account
          uri: http://localhost:8091/api/savings
          predicates:
          - Path=/api/savings/**
          filters: StripPrefix=2
server:
  port: 8097
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
