server:
  port: 8090
spring:
  application:
    name: servicio-Customer
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbcustomer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka