server:
  port: 8092
spring:
  application:
    name: servicio-Credits
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbcredits

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka